### ISSUE TITLE
Howto secure HTTP nodes in this embedded template?

### ISSUE THREAD

**Issue by khelkun** [TotallyInformation/node-red-template-embedded#4]
Hello and thanks for the template.

I try to figure out how I could secure the  HTTP nodes of the node-red instance embedded in ExpressJS.
As stated by the doc and your README, I see that securing the acces to the admin UI with the node-red setting "adminAuth" works fine but httpNodeAuth cannot be used in embedded node-red. Could you give me an hint on how to achieve this in ExpressJS please?

**Comment by TotallyInformation** [comment]
Apologies for not responding to this. Please refer to the [Node-RED forum](TotallyInformation/node-red-template-embedded) for discussions on this subject. Thanks.
